git:
  depth: false

if: branch = master

branches:
  only:
    - master

env:
  global:
    - CI_SOURCE_PATH=$(pwd)
    - CI_PARENT_DIR=.travis

jobs:
  include:
    - name: "Dummy Test"
      dist: bionic
      language: bash
      python: "2.7.15"
      env:
        - TEST=build
      script:
        - $CI_PARENT_DIR/$TEST.sh