git:
  depth: false

if: branch = master

branches:
  only:
    - master

jobs:
  include:
    - name: "Dummy Test"
      dist: bionic
      language: bash
      python: "2.7.15"
      services: docker
      env:
      - TEST=build
      script:
        - $TEST.sh